"""Build the berlin (full-city) background route file from BeST.

Streams the full BeST berlin.rou.gz (2.25M vehicles / 24h) and keeps only:
  - vehicles departing inside [--begin, --end] (SUMO discards pre-begin
    departs anyway; filtering kills the multi-minute startup parse), and
  - a deterministic ~keep-percent sample (stable sha1 hash of vehicle id),
    because we simulate background traffic as visual context — the public
    frame caps how many are ever shown, and full-volume Berlin steps at
    ~1.7x realtime which makes recording impractical.

Robotaxis and MATSim person demand are not touched by this thinning.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import time
import xml.etree.ElementTree as ET
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = Path(
    r"C:\Users\KitCat\Desktop\Projects\EV Mobility Dashboard\data\raw\best-scenario\scenario\sumo\berlin.rou.gz"
)
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "hf-space" / "app" / "sumo" / "berlin"


def stable_sample_key(value: str) -> int:
    # Same deterministic hash as hf-space/app/main.py:237.
    return int(hashlib.sha1(value.encode("utf-8")).hexdigest()[:8], 16)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_DIR / "berlin-background.rou.xml")
    parser.add_argument("--begin", type=int, default=63_600, help="keep departs >= this (17:40)")
    parser.add_argument("--end", type=int, default=68_400, help="keep departs < this (19:00)")
    parser.add_argument("--keep-percent", type=int, default=12)
    args = parser.parse_args()

    args.output.parent.mkdir(parents=True, exist_ok=True)
    stats = {
        "source": str(args.source),
        "begin": args.begin,
        "end": args.end,
        "keepPercent": args.keep_percent,
        "vehiclesScanned": 0,
        "vehiclesInWindow": 0,
        "vehiclesKept": 0,
    }
    started = time.perf_counter()
    vtypes: list[str] = []
    wrote_vtypes = False

    with gzip.open(args.source, "rt", encoding="utf-8") as source, args.output.open(
        "w", encoding="utf-8", newline="\n"
    ) as out:
        out.write('<?xml version="1.0" encoding="UTF-8"?>\n')
        out.write(
            f"<!-- generated by build_berlin_routes.py; departs [{args.begin},{args.end}), "
            f"deterministic {args.keep_percent}% sample of BeST berlin.rou.gz -->\n"
        )
        out.write(
            '<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
            'xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">\n'
        )
        root = None
        for event, elem in ET.iterparse(source, events=("start", "end")):
            if root is None and event == "start":
                root = elem
                continue
            if event != "end":
                continue
            if elem.tag == "vType":
                vtypes.append(ET.tostring(elem, encoding="unicode"))
                elem.clear()
                continue
            if elem.tag != "vehicle":
                if elem.tag != "route":
                    elem.clear()
                if root is not None:
                    root.clear()
                continue

            stats["vehiclesScanned"] += 1
            depart = float(elem.attrib.get("depart", "0"))
            if args.begin <= depart < args.end:
                stats["vehiclesInWindow"] += 1
                vehicle_id = elem.attrib.get("id", "")
                if stable_sample_key(vehicle_id) % 100 < args.keep_percent:
                    if not wrote_vtypes:
                        for vtype in vtypes:
                            out.write(f"    {vtype}\n")
                        wrote_vtypes = True
                    out.write(f"    {ET.tostring(elem, encoding='unicode')}\n")
                    stats["vehiclesKept"] += 1
            elif depart >= args.end:
                # Departs are sorted ascending; nothing after the window matters.
                elem.clear()
                break
            elem.clear()
            if root is not None:
                root.clear()
        out.write("</routes>\n")

    stats["outputBytes"] = args.output.stat().st_size
    stats["runtimeSeconds"] = round(time.perf_counter() - started, 1)
    metadata_path = args.output.with_suffix(".metadata.json")
    metadata_path.write_text(json.dumps(stats, indent=2), encoding="utf-8")
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
