from __future__ import annotations

import argparse
import gzip
import json
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, TextIO


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCENARIO_KEY = "charlottenburg-moabit-tiergarten"
INTERMEDIATE_DIR = PROJECT_ROOT / "data" / "intermediate" / "sumo" / SCENARIO_KEY
BUILD_PLAN = INTERMEDIATE_DIR / f"{SCENARIO_KEY}.sumo-build-plan.json"
SERVICE_EDGES = INTERMEDIATE_DIR / f"{SCENARIO_KEY}.service-edges.txt"
DEFAULT_OUTPUT = INTERMEDIATE_DIR / f"{SCENARIO_KEY}.service-contained.rou.xml"
DEFAULT_METADATA = INTERMEDIATE_DIR / f"{SCENARIO_KEY}.service-contained.routes.metadata.json"


def load_json(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def load_edge_ids(path: Path) -> set[str]:
    return {
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }


def open_maybe_gzip(path: Path):
    if str(path).endswith(".gz"):
        return gzip.open(path, "rt", encoding="utf-8")
    return path.open("r", encoding="utf-8")


def route_edges(vehicle: ET.Element) -> list[str]:
    route = vehicle.find("route")
    if route is None:
        return []
    return [edge for edge in route.attrib.get("edges", "").split() if edge]


def write_header(out: TextIO) -> None:
    out.write('<?xml version="1.0" encoding="UTF-8"?>\n')
    out.write(
        "<!-- generated by filter_charlottenburg_moabit_tiergarten_routes.py; "
        "strict-contained serviceEdges only -->\n"
    )
    out.write(
        '<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/routes_file.xsd">\n'
    )


def filter_routes(
    source_routes: Path,
    service_edges: set[str],
    output_path: Path | None,
    max_vehicles: int | None,
) -> dict[str, Any]:
    stats: dict[str, Any] = {
        "sourceRoutes": str(source_routes.resolve()),
        "routeFilterEdgeSet": "serviceEdges",
        "serviceEdges": len(service_edges),
        "dryRun": output_path is None,
        "maxVehicles": max_vehicles,
        "vehiclesScanned": 0,
        "vehiclesKept": 0,
        "vehiclesRejected": 0,
        "vehiclesWithoutRoute": 0,
        "firstKeptDepart": None,
        "lastKeptDepart": None,
        "keptVehicleIdsSample": [],
    }
    vtypes: list[str] = []
    wrote_vtypes = False
    out: TextIO | None = None

    try:
        if output_path is not None:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            out = output_path.open("w", encoding="utf-8", newline="\n")
            write_header(out)

        with open_maybe_gzip(source_routes) as source:
            root = None
            for event, elem in ET.iterparse(source, events=("start", "end")):
                if root is None and event == "start":
                    root = elem
                    continue
                if event != "end":
                    continue

                if elem.tag == "vType":
                    vtypes.append(ET.tostring(elem, encoding="unicode"))
                    elem.clear()
                    continue

                if elem.tag != "vehicle":
                    if elem.tag != "route":
                        elem.clear()
                    if root is not None:
                        root.clear()
                    continue

                stats["vehiclesScanned"] += 1
                edges = route_edges(elem)
                if not edges:
                    stats["vehiclesWithoutRoute"] += 1

                if edges and all(edge in service_edges for edge in edges):
                    if out is not None:
                        if not wrote_vtypes:
                            for vtype in vtypes:
                                out.write(f"    {vtype}\n")
                            wrote_vtypes = True
                        out.write(f"    {ET.tostring(elem, encoding='unicode')}\n")
                    stats["vehiclesKept"] += 1
                    depart = elem.attrib.get("depart")
                    stats["firstKeptDepart"] = stats["firstKeptDepart"] or depart
                    stats["lastKeptDepart"] = depart
                    if len(stats["keptVehicleIdsSample"]) < 20:
                        stats["keptVehicleIdsSample"].append(elem.attrib.get("id"))
                else:
                    stats["vehiclesRejected"] += 1

                elem.clear()
                if root is not None:
                    root.clear()

                if max_vehicles is not None and stats["vehiclesScanned"] >= max_vehicles:
                    stats["stoppedEarly"] = True
                    break
            else:
                stats["stoppedEarly"] = False

        if out is not None:
            out.write("</routes>\n")
            stats["outputRoutes"] = str(output_path.resolve())
    finally:
        if out is not None:
            out.close()
            if output_path is not None:
                stats["outputBytes"] = output_path.stat().st_size if output_path.exists() else 0

    return stats


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Filter BeST background routes for the Charlottenburg + Moabit + Tiergarten "
            "service cutout. This intentionally uses serviceEdges, not activeEdges."
        )
    )
    parser.add_argument("--build-plan", type=Path, default=BUILD_PLAN)
    parser.add_argument("--service-edges", type=Path, default=SERVICE_EDGES)
    parser.add_argument("--source-routes", type=Path, default=None)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--metadata", type=Path, default=DEFAULT_METADATA)
    parser.add_argument("--max-vehicles", type=int, default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    build_plan = load_json(args.build_plan)
    source_routes = args.source_routes or Path(build_plan["source"]["sourceRoutes"])
    if not source_routes.exists():
        raise FileNotFoundError(source_routes)
    service_edges = load_edge_ids(args.service_edges)
    if not service_edges:
        raise RuntimeError(f"No service edges loaded from {args.service_edges}")

    output_path = None if args.dry_run else args.output
    stats = filter_routes(source_routes, service_edges, output_path, args.max_vehicles)
    stats.update(
        {
            "scenarioKey": SCENARIO_KEY,
            "serviceEdgesPath": str(args.service_edges.resolve()),
            "activeEdgesNotUsed": True,
            "guardrail": (
                "Background traffic uses strict-contained serviceEdges only. "
                "Depot connector edges from activeEdges are excluded."
            ),
            "packagingComplete": not args.dry_run and not stats.get("stoppedEarly", False),
        }
    )

    args.metadata.parent.mkdir(parents=True, exist_ok=True)
    args.metadata.write_text(json.dumps(stats, indent=2), encoding="utf-8")
    print(json.dumps(stats, indent=2))


if __name__ == "__main__":
    main()
